// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKBcY4Te9P-yN7AYFJJBAnP4oFflIfVI',
    appId: '1:968343947838:web:2b2a39cba60f27c89edf6f',
    messagingSenderId: '968343947838',
    projectId: 'chat-app-ad5ca',
    authDomain: 'chat-app-ad5ca.firebaseapp.com',
    storageBucket: 'chat-app-ad5ca.appspot.com',
    measurementId: 'G-W0D137EPW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqxLflhHW7FNcmwoBGmTNaTMmjT6pvYIo',
    appId: '1:968343947838:android:47310c55db8c61f69edf6f',
    messagingSenderId: '968343947838',
    projectId: 'chat-app-ad5ca',
    storageBucket: 'chat-app-ad5ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwrAk7dfbmf5adGVOG4dx2q9DTFNadChk',
    appId: '1:968343947838:ios:0d051b2b742b0c9c9edf6f',
    messagingSenderId: '968343947838',
    projectId: 'chat-app-ad5ca',
    storageBucket: 'chat-app-ad5ca.appspot.com',
    iosClientId: '968343947838-f3o3ommh6imf1luvbtbjg47duufq8j7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwrAk7dfbmf5adGVOG4dx2q9DTFNadChk',
    appId: '1:968343947838:ios:0d051b2b742b0c9c9edf6f',
    messagingSenderId: '968343947838',
    projectId: 'chat-app-ad5ca',
    storageBucket: 'chat-app-ad5ca.appspot.com',
    iosClientId: '968343947838-f3o3ommh6imf1luvbtbjg47duufq8j7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
